# syntax=docker/dockerfile:1
ARG NODE_VERSION=24.0.0

FROM node:${NODE_VERSION}-alpine
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source
COPY . .

# Expose Vite dev server
EXPOSE 5173

# Start dev server
CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]
